✨ [Feature] delete block user API
GhostPangPang/GhostPong pull request #108
Opened 2023-04-20 11:51 UTC by anso33

## Summary
차단한 유저를 해제하는 API 구현

## Describe your changes
- `/blocked/(user_id)` 구현

- 다른 레포지토리를 사용할 때 우선은 레포지토리는 본인(A) 도메인 레포지토리만 사용하고 남(B)의 레포지토리는  BService를 가져다가 사용하도록 했는데요. 이때 import 하는 범위를 현재는 Module로 하고 있습니다. 계속 module을 import 받아 BService를 사용하는 방식으로 진행할지 아니면 그냥 import 없이 BRepository를 가져다 쓸지는 각 방법의 장단점을 **좀 더 공부해보고 위키 작성 후 리팩토링하도록 하겠습니다.**    아무튼 현재는 모듈을 import 받고 BService(남의 서비스 클래스)를 가져다가 사용하는 방식으로 진행하겠습니다. 

- 두 모듈간의 순환 참조에 대해서도 우선 서버가 돌아가도록 두개 모두 forwardRef() 처리를 해놓고 자세한 이유는 더 공부해서 위키에 적도록 하겠습니다. 

- createUser() in UserService에서 transaction 처리 해놨습니다. 

## Issue number and link
- close #106

2023-04-20 13:59 UTC, jis-kim requested changes
코멘트 확인 부탁드립니다!
그리고 테스트 하다가 발견했는데 swagger 가 `NicknameRequestDto` 의 형식을 인식하지 못하는 부분이 있던데, `@Match` 로 정규표현식 이용해서 검증하는 부분을 바꾸면 해결이 됩니다. `@Matches(/^[가-힣a-zA-Z0-9]*$/)`로 변경 부탁드립니다. 변경이유는 객체를 생성하면 swagger cli 가 못알아 먹기도 하고 리터럴로 하는 방식이 더 효율적일 것이라고 생각해서입니다! 정규표현식에 관한 부분은 [참고](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Regular_expressions) 해주세요!

2023-04-20 13:59 UTC, jis-kim commented on backend/src/blocked/blocked.service.ts
> +      throw new NotFoundException('차단한 적이 없는 유저입니다.');
이거 먼가.................."차단 기록이 없는 유저입니다" 어떨까요? 아님 "해당 유저의 차단 기록이 없습니다." 도 괜찮을 것 같습니다.

2023-04-20 13:59 UTC, jis-kim commented on backend/src/blocked/blocked.service.ts
> +    await this.userService.findExistUserById(userId);
`userId` 가 없으면 뒤의 `NotFoundException` 에서 걸러질 것 같은데 `User` 가 있는지까진 판단하지 않아도 되지 않을까요? 에러메세지를 분리하고 싶다면 이렇게 해야될 것 같긴한데 음....차단해제 로직에서 꼭 체크할 부분은 아니라고 생각합니다. 제 개인의견입니다..!

2023-04-20 13:59 UTC, jis-kim commented on backend/src/blocked/blocked.service.ts
> +    await this.blockedUserRepository.delete(blockedUser);
앗 delete 에 `blockedUser` 엔티티를 그냥 바로 넣어도 되나요?

`friend` API 로 실험 결과 Entity 를 그냥 삽입하면 where 절에 entity 의 모든 값이 들어가는 군요.. id 만 전달하는 방향으로 수정해주세요! where 절에 조건 하나만 있는 편이 훨씬 빠를 것 같습니다.

1. entity 를 그대로 넘겼을 때 -> 전체 조건으로 인식되어서 where 조건 여러개로 쿼리 실행
<img width="525" alt="Screenshot 2023-04-20 at 10 27 44 PM" src="https://user-images.githubusercontent.com/71019735/233381062-41920295-2f80-4229-bb3f-60f4f5556261.png">

2. id 만 넘길 경우 -> 인덱싱된 id 로 찾아서 삭제
<img width="508" alt="Screenshot 2023-04-20 at 10 30 41 PM" src="https://user-images.githubusercontent.com/71019735/233381854-ca6df427-c6ec-4f27-9731-f59e5d6f27cf.png">

```suggestion
    await this.blockedUserRepository.delete(blockedUser.id);
```

2023-04-20 13:59 UTC, jis-kim commented on backend/src/blocked/blocked.service.ts
> +  async findBlockedByUserId(userId: number): Promise<number[]> {
이거 사소하지만 이름 변경 가능할까요?
```suggestion
  async findBlockedIdByUserId(userId: number): Promise<number[]> {
```

2023-04-20 13:59 UTC, jis-kim commented on backend/src/user/user.service.ts
> +      await manager.save(user);
여기 이전 방법으로 그냥 `{ id: authId.. }` 로 안하고 `constructor` 만들어서 하신 이유가 궁금합니다!!

2023-04-20 14:47 UTC, jis-kim commented on backend/src/user/user.service.ts
> +      await manager.save(user);
`manager` 의 메서드를 써야 롤백이 된다면 뒤에 `changeAuthStatus` 에서는 적용을 안시켜줘도 되나요? 어차피 `changeAuthStatus` 뒤에 추가로 insert 로직이 없어서 그냥 처리하신 걸까요??
그리고 entity 째로 넣고 싶으시면 `userRepository.create()` 메소드를 사용하시는 편이 나았을 것 같고 아니면 `UserEntity` 에 `exp` 프로퍼티를 optional 으로 바꿔서 (`exp?: number` 로 변경) 객체 리터럴로 입력하면 constructor 없이 작동할 것 같습니다.

2023-04-20 15:35 UTC, jis-kim commented on backend/src/user/user.service.ts
> +      await manager.save(user);
으음 근데 생각해보니까 nullable 이 아닌 `exp` 에 `?`을 붙이는 건 좀 아닌 것 같네요.. `create()` 쪽이나 다른 방법을 고려해주시길 바랍니다!

2023-04-21 01:44 UTC, Kimhan-nah commented on backend/src/blocked/blocked.service.ts
> +      throw new NotFoundException('차단한 적이 없는 유저입니다.');
또는 "차단된 유저가 아닙니다" ??

2023-04-21 01:52 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +      throw new NotFoundException('차단한 적이 없는 유저입니다.');
차단된 유저가 아닙니다 로 수정하겠습니다ㅎㅎ 이말이 하고 싶었는데 생각이 안났었어요
ㅋㅋㅋㅋㅋ

2023-04-21 01:56 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +    await this.userService.findExistUserById(userId);
엄 저 체크를 안하면 차단된 유저가 아니라는 에러를 응답하게 되는데요. 그것보다는 없는 유저면 없는 유저라고 에러 응답하는게 맞다고 생각해서 남겨두겠숩니당!

2023-04-21 02:09 UTC, Kimhan-nah reviewed
확인했습니당~~

2023-04-21 02:09 UTC, Kimhan-nah commented on backend/src/blocked/blocked.controller.ts
> +  @ApiNotFoundResponse({ type: ErrorResponseDto, description: '차단한 적이 없는 유저, 존재하지 않는 유저' })
'차단한 적이 없는 유저' -> '차단되지 않은 유저' 또는 '차단되지 않은 유저를 해제할 때' 가 더 이해하기 좋을 것 같아용ㅎㅎ

2023-04-21 02:09 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +      await manager.save(user);
댓글 보고 생각해봤는데 지수님 언급했듯이 typeorm create 함수로 충분히 entity 만들 수 있어서 entity에 constructor 추가 안하는 게 다른 entity와도 통일성 있고 좋을 것 같아용!

2023-04-21 02:12 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +    await this.blockedUserRepository.delete(blockedUser);
아 근데 blocked user 테이블이 컬럼이 userid와 blockedUserId 밖에 없고 두컬럼이 복합으로 pk라서 그냥 이렇게 delete하는게 pk 쓰는 것과 같습니다. 그리고 이렇게 해야 에러 없이 delete 할 수 있어요! 복합키라서 그런듯 합니다.

2023-04-21 02:13 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +  async findBlockedByUserId(userId: number): Promise<number[]> {
아ㅏ 인정입니다...ㅎ..

2023-04-21 02:14 UTC, Kimhan-nah commented on backend/src/blocked/blocked.service.ts
> +    await this.userService.findExistUserById(userId);
아니면 에러 메세지를 수정하는 건 어떻게 생각하시나용??
왜냐면 유저가 엄청 많아졌을 경우에 굳이 find 하지 않아도 차단 목록에서 걸러질텐데 불필요한 게 아닐까... 생각이 드는데
그래도 우선순위가 에러 메세지 구분하는 게 높다면 그대로 진행해도 좋아요!

2023-04-21 02:17 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +    await this.userService.findExistUserById(userId);
오 삭제하고 에러 메세지 변경하는 방향으로 가겠습니ㅏ다.

2023-04-21 02:19 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +    await this.userService.findExistUserById(userId);
그렇다면 차단한 기록이 없습니다 라는 에러 메세지로 유저 없음이라는 에러와 차단한 기록이 없는 유저임을 표현하겠습니다!

2023-04-21 02:21 UTC, Kimhan-nah commented on backend/src/blocked/blocked.service.ts
> +    await this.userService.findExistUserById(userId);
"차단 목록에 존재하지 않는 유저입니다" 어때요 ㅎㅎㅎ??

2023-04-21 02:22 UTC, Kimhan-nah commented on backend/src/blocked/blocked.service.ts
> +    await this.userService.findExistUserById(userId);
"차단된 유저가 아닙니다" 보다는 그래도 "차단 목록에 존재하지 않는 유저입니다"가 좀더 두가지 의미를 담고 있는 것 같지 않나요 ㅎㅎㅎ?

2023-04-21 02:24 UTC, anso33 commented on backend/src/user/user.service.ts
> +      await manager.save(user);
> 롤백이 된다면 뒤에 changeAuthStatus 에서는 적용을 안시켜줘도 되나요? 어차피 changeAuthStatus 뒤에 추가로 insert 로직이 없어서 그냥 처리하신 걸까요??

맞습니다. 일단은 원하는대로 트랜젝션 처리가 되는 걸로 확인했는데 저렇게 쓰는게 최선인지는 트랜젝션을 좀 더 공부해보고 더 좋은 방법이 있으면 리팩토링 해보겠읍니다..ㅎㅎ 일단 기한내에  마무리먼저 해야할 것 같아서.... 위키에 달아놓겠습니다1!

2023-04-21 02:27 UTC, jis-kim commented on backend/src/blocked/blocked.service.ts
> +    await this.blockedUserRepository.delete(blockedUser);
아하 그렇네요!! 그렇다면 db 구조가 변경되지 않는 이상 괜찮을...것 같긴 하지만 entity에는 다른 프로퍼티들이 추가될 가능성도 있어서 id 랑blockedUserId로 criteria 를 명시해주셨으면 합니다!

2023-04-21 03:04 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +    await this.userService.findExistUserById(userId);
유저라는 말이 존재하는 유저라는 말 같아서 그냥 차단기록이 없습니다 로 통일했습니다. 
본의 아니게 커밋이 좀 많아졌는데 ㅎㅎ 수정시 커밋 단위에 대해서 좀더 고려해보겠습니다.ㅎㅎ

2023-04-21 03:13 UTC, anso33 commented
리뷰를 너무 빨리 반영하다보니...ㅋㅋㅋㅋㅋㅋㅋㅋㅋ음...네...커밋이 과도해졌는데요.... 앞으로는 신중히 커밋을 하겠습니다......

그리고 혹시나 해서 남기는데 (deleteBlockedUser in blocked.service) delete에서 굳이 blockedUser 객체의 값을 가져다 쓴 이유는 찾은 blockedUser (record)를 삭제하겠다는 강한 의지를 표현한겁니다..ㅎㅎ

@jis-kim @Kimhan-nah

2023-04-21 07:28 UTC, Kimhan-nah approved these changes
확인했습니당

2023-04-21 09:29 UTC, jis-kim approved these changes
확인완료!! 수고 많으셨어요

2023-04-21 09:38 UTC, anso33 commented
끼얏호!

2023-04-21 09:38 UTC, merged