✨ [Feature] loby page
GhostPangPang/GhostPong pull request #116
Opened 2023-04-21 21:22 UTC by nyeoni

## Summary
- Loby Page 구현

## Describe your changes
- Loby Page 구현
 - Router 적용
 - MainLayout 구현
- Grid 컴포넌트 수정
- `theme` 에 `gray` 추가
  - 이유 : 기존에 투명도가 있던 `surface` 외에 투명도가 없는 색 필요
- ps) 나중에 Layout 적용 컨벤션 및 데이터 패치 어디서 할지 같이 이야기해보고 결정해야함

## Issue number and link
- #87

2023-04-22 06:08 UTC, aLVINlEE9 requested changes
코멘트 확인해주세요

2023-04-22 06:08 UTC, aLVINlEE9 commented on frontend/src/layout/Header/Header.tsx
>        <Logo />
아바타, 드롭박스, 프로그래스바 추가해주세영~

2023-04-22 06:47 UTC, nyeoni commented on frontend/src/layout/Header/Header.tsx
>        <Logo />
okay~~~~~~~

2023-04-22 10:03 UTC, yongjulejule requested changes
LGTM

2023-04-22 10:04 UTC, jis-kim approved these changes
LGTM

2023-04-24 09:39 UTC, aLVINlEE9 requested changes
커멘트 확인해주세용!!

2023-04-24 09:39 UTC, aLVINlEE9 commented on frontend/src/pages/LobbyPage/LobbyPage.tsx
> +};
아래 사진과 같이 버튼 위치가 바닥 기준으로 위에 있는것 같습니다.
이게 storybook의 문제인지 Grid컴포넌트의 문제인지 잘 모르겠습니다. 확인 부탁드릴게요~~
<img width="732" alt="image" src="https://user-images.githubusercontent.com/74805318/233959098-42fd1d12-34a1-4757-b31f-22cd092aeb7b.png">

2023-04-24 09:45 UTC, nyeoni commented on frontend/src/pages/LobbyPage/LobbyPage.tsx
> +};
`Storybook` 문제입니다~ 이 부분 storybook-addon 수정중에 있습니다.

2023-04-24 09:46 UTC, nyeoni commented
@aLVINlEE9  DropBoxProps 와 같은 common 컴포넌트의 Props 들은 다 export 처리 부탁드릴게요! DropBox 같은 경우는 제가 수정해서 올렸습니다 :)

2023-04-24 12:48 UTC, nyeoni commented on frontend/src/pages/LobbyPage/LobbyPage.tsx
> +};
react18 + yarn pnp 환경에 맞는 storybook-addon 이 없는걸로 보입니다. 이 부분은 나중에 cypress 나 vercel 로 배포하면서 확인하는 방향으로 하려합니다.

2023-04-24 12:49 UTC, aLVINlEE9 commented on frontend/src/pages/LobbyPage/LobbyPage.tsx
> +};
넵 고생하셨습니다~

2023-04-24 12:49 UTC, aLVINlEE9 approved these changes

2023-04-24 12:49 UTC, merged