✨ [Feature] ProfilePage Implementation
GhostPangPang/GhostPong pull request #147
Opened 2023-04-26 15:58 UTC by aLVINlEE9

## Summary
프로필 페이지 뷰를 완성하였습니다.

## Describe your changes
- 프로필 페이지 뷰
- dummy data 넣어보기
- Rank Util 만듬 
  - rank exp 관련된, 유틸 함수와 컴포넌트 모두 `src/pages/RankUtil` 이 디렉토리에 넣어두었습니다. 나중에 이동 필요

<img width="579" alt="image" src="https://user-images.githubusercontent.com/74805318/234633095-01575720-15f9-4c9d-b20d-1487e1045f0a.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/74805318/235664923-d2dfbafa-6ed5-4269-8fd3-ad35b5b56746.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/74805318/235664843-77d5825c-86af-4451-93d6-95986813f4f5.png">

## Issue number and link
- #128

2023-05-03 07:30 UTC, nyeoni requested changes
나머지 세부 사항에 대해서 내일 같이 회의하면서 결정해봐요! 고생하셨습니다 :)

2023-05-03 07:30 UTC, nyeoni commented on frontend/src/pages/RankUtil/RankUtil.tsx
> +export const RankBadge = ({ rank, width = 'auto', height = 'auto' }: RankBadgeProps) => {
`util` 잘 빼신 것 같습니다! 다만 RankBadge 같은 경우 유틸리티 함수가 아닌 jsx 컴포넌트이므로 common 에 RankBadge 컴포넌트를 따로 만들어 주시면 좋을 것 같습니다!

2023-05-03 07:47 UTC, jis-kim commented
페이지가 귀여워요 뱃지 은은하게 후광 도는 게 마음에 들어요 프론트짱

2023-05-05 09:03 UTC, nyeoni approved these changes

2023-05-05 09:03 UTC, nyeoni commented on frontend/src/pages/ProfilePage/InfoBox/InfoBox.tsx
> +type InfoBoxProps = {
저희 컴포넌트 Props 는 interface 로 해주시고, export 해주세요~!!

2023-05-05 09:24 UTC, merged