✨ [Feature] 42 OAuth Login with JWT Token
GhostPangPang/GhostPong pull request #158
Opened 2023-04-30 09:28 UTC by Kimhan-nah

## Summary
- 42 OAuth 로그인 구현

## Describe your changes
- 42 OAuth 로그인 
- JWT 토큰 발급 및 검증

## Issue number and link

2023-05-01 06:44 UTC, jis-kim commented on backend/src/auth/auth.controller.ts
> +    if (user.id === null) {
이거 `user` 가 `undefined` 이면 error 가 날 것 같은데 `undefined` 일 일이 없을까요?

2023-05-01 07:55 UTC, jis-kim requested changes
드디어 pr 이!!!!!!!!!!!!!!! 댓글 확인 부탁드립니다 정말 수고하셨어요~~~ auth 의 달인 hannkim!

2023-05-01 07:55 UTC, jis-kim commented on backend/src/user/user.service.ts
>      private readonly authService: AuthService,
요기 없어도 될 것 같아요!

2023-05-01 07:55 UTC, jis-kim commented on backend/src/user/user.module.ts
> +    forwardRef(() => AuthModule),
`UserService` 에서 `AuthService` 삭제하면 여기도 삭제 가능할 것 같습니다.

2023-05-01 07:55 UTC, jis-kim commented on backend/src/auth/strategy/user.strategy.ts
> +    return token;
```suggestion
    return { userId: payload.userId };
```
제안드립니다. token 선언해서 명확한 게 좋다면 안하셔두됩니다잇

2023-05-01 07:55 UTC, jis-kim commented on backend/src/common/decorator/auth.decorator.ts
> +  console.log(request);
요것도 지워주세요!! ^.^

2023-05-01 07:55 UTC, jis-kim commented on backend/src/common/decorator/auth.decorator.ts
> +export const ReqToken = createParamDecorator<string>((data, ctx) => {
이건 어디서 쓰이고 있나요?? `token` 이라는 걸 request 에 저장하는 부분이 있는 지도 모르겠습니다. 제가 발견 못한거라면 알려주세요!

2023-05-01 07:55 UTC, jis-kim commented on backend/src/auth/dto/login-info.dto.ts
> +  id: number | null;
여기는 validate 할 부분이 없을까요??

2023-05-01 07:55 UTC, jis-kim commented on backend/src/auth/strategy/auth.strategy.ts
> +      // ignoreExpiration: false,
이거 필요한 지 확인해주세요!

2023-05-01 07:55 UTC, jis-kim commented on backend/src/config/app/configuration.module.ts
> +        CLIENT_PORT: Joi.number().default(5000),
`CLIENT_PORT` 를 login 에서 redirect 할 때 사용하셨는데, 불필요한 이유를 같이 이야기 나눴습니다! 제거하게 된다면 `AppConfig` 를 다른 `Service` 나 `Controller` 에서 사용하는 부분도 같이 제거해주세요!!

2023-05-01 07:55 UTC, jis-kim commented on backend/src/user/dto/login-request.dto.ts
> +export class LoginRequestDto {
이거 안쓰는 클래스네요!! 삭제 부탁드려요

2023-05-01 07:55 UTC, jis-kim commented on backend/src/user/dto/user-nickname-response.dto.ts
> +  }
여기 conflict 해결과정에서 다시 생긴 것 같아요 삭제 부탁드립니다!!

2023-05-01 07:55 UTC, jis-kim commented on backend/src/user/user.controller.ts
> +    res.clearCookie('jwt-for-unregistered').redirect(`http://localhost:${clientPort}/auth?token=${token}`);
여기 `redirect()` path 형식으로 바꿔주세요!!

2023-05-01 08:01 UTC, jis-kim commented on backend/src/auth/decorator/auth.decorator.ts
> +export const ReqUser = createParamDecorator<string>((data, ctx) => {
```suggestion
export const ExtractUser = createParamDecorator<string>((data, ctx) => {
```
이름 변경 제안드립니다!!

2023-05-01 08:10 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
>      private readonly authService: AuthService,
`authService.signIn` 함수 사용하고 있어서 필요합니다!

2023-05-01 12:02 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
> +    console.log('42Login!');
넵넵 알겠습니당 ㅎ.ㅎ

2023-05-01 12:42 UTC, Kimhan-nah commented on backend/src/user/dto/user-nickname-response.dto.ts
> +  }
넵 확인했습니다아

2023-05-01 13:15 UTC, Kimhan-nah commented on backend/.env.example
> +USER_JWT_EXPIREIN=
네에 확인했습니다 적용했습니닷

2023-05-01 13:17 UTC, Kimhan-nah commented on backend/src/user/dto/login-request.dto.ts
> +export class LoginRequestDto {
custom decorator과 새로운 type 추가하려고 만들었던 파일들 우선 삭제하고 다음 PR에 적용시키겠습니다!

2023-05-01 13:32 UTC, Kimhan-nah commented on backend/src/common/decorator/auth.decorator.ts
> +  console.log(request);
이것도 다음 PR에서 필요할 때 파일 만들고 일단은 삭제하겠습니다!

2023-05-01 13:36 UTC, Kimhan-nah commented on backend/src/auth/dto/login-info.dto.ts
> +  id: number | null;
`@IsOptional()`과 `@IsNumber()` 추가하겠습니다!

2023-05-01 13:42 UTC, Kimhan-nah commented on backend/src/auth/strategy/auth.strategy.ts
> +      // ignoreExpiration: false,
default 값이 false라서 지우겠습니다!
`ignoreExpiration`가 false 이면, verify 함수를 호출하여 만료된 JWT를 검증하려고 시도할 때 `TokenExpiredError` 오류가 발생합니다!

2023-05-01 13:45 UTC, Kimhan-nah commented on backend/src/config/app/configuration.module.ts
> +        CLIENT_PORT: Joi.number().default(5000),
넵 수정 완료했습니다아

2023-05-01 13:46 UTC, Kimhan-nah commented on backend/src/user/user.controller.ts
> +    res.clearCookie('jwt-for-unregistered').redirect(`http://localhost:${clientPort}/auth?token=${token}`);
수정 완료 했습니다아

2023-05-01 13:53 UTC, Kimhan-nah commented on backend/src/auth/decorator/auth.decorator.ts
> +export const ReqUser = createParamDecorator<string>((data, ctx) => {
너무 좋아용 네이밍 추천 감삼다~~

2023-05-01 15:28 UTC, jis-kim requested changes
재리뷰 완료했습니다. 댓글 확인 다시 부탁드려요!!

2023-05-01 15:28 UTC, jis-kim commented on backend/src/auth/auth.controller.ts
> +          sameSite: 'none',
이거 보안강화된 쿠키를 만들기 위한 것 같은데 [쿠키속성](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie) 을 보시면 sameSite 이 none 일 때는 다른 사이트로 가는 요청에서도 해당 쿠키가 보내진다고 되어있습니다. 의도하신 건 lax나 strict 의 동작같은데 확인해주실 수 있을까요?

2023-05-01 15:28 UTC, jis-kim commented on backend/src/auth/auth.controller.ts
> +    if (user.id === null) {
`/auth/42login/callback` 으로 직접적인 요청이 오거나 하는 경우가 있지 않을까요? 물론 나중에 직접 접근하는 경우를 애초부터 막아버리는 로직을 추가할 수도 있겠지만... 아무튼 `user` 가 `undefined`이면 런타임 에러가 발생해버리고 status code 500이 response 로 가버리겠죠!
저는 런타임 에러는 최대한 막아주는 것이 좋다고 생각해서요, 에러처리의 관점에서 말씀 드린 것이었습니다!!

2023-05-01 15:28 UTC, jis-kim commented on backend/src/config/app/configuration.ts
> +  appPort: process.env.APP_PORT,
요거 혹시 다시 port 로 바꿔주실 수..있나요 ㅎㅎ

2023-05-01 15:28 UTC, jis-kim commented on backend/src/auth/decorator/auth.decorator.ts
> +  return data ? user?.[data] : user;
여기서 만약 `request` 에 `user` 가 없으면 `user?.[data]` 가 `undefined` 가 되어서 위의 `/auth/42login/callback` 에 `undefined` 가 올 가능성이 충분히 있다고 생각합니다.

2023-05-02 02:12 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
> +    if (user.id === null) {
`/auth/42login/callback`으로 직접 테스트 해봤는데 42 guard 때문에 인트라 로그인으로 가서 undefined일 경우가 생기지 않을 것 같아요..!

2023-05-02 02:25 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
> +    if (user.id === null) {
callback에서 문제가 되지 않겠지만 만약 해당 decorator를 다른 곳에서도 사용할 경우 undefined가 가능할 수 있을 것 같네용
그럼 default 값을 주는 방법과 error throw하는 것 중에 후자로 할까요???

2023-05-02 03:48 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
> +    if (user.id === null) {
해당 decorator는 passport를 거칠 때에만 사용하는 decorator라서 에러 처리를 안 하는 방향으로 얘기했습니다.
다른 곳에서 해당 decorator를 사용하지 않는 걸로 하겠습니다!

2023-05-02 04:26 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
> +          sameSite: 'none',
넵넵 확인했습니다! `strict`로 수정했습니다

2023-05-02 04:28 UTC, Kimhan-nah commented on backend/src/config/app/configuration.ts
> +  appPort: process.env.APP_PORT,
넵 수정하겠습니다아

2023-05-02 04:33 UTC, Kimhan-nah commented on backend/src/auth/decorator/auth.decorator.ts
> +  return data ? user?.[data] : user;
다른 comment에서 얘기 나눠서 에러 핸들링 필요 없다는 결론 내렸습니닷! 다만 `data` parameter를 쓸 일이 없을 거 같아서 user만 return 하도록 수정하겠습니다

2023-05-02 04:43 UTC, yongjulejule commented on backend/src/auth/auth.controller.ts
> +          sameSite: 'none',
프론트와 쿠키 전송에 문제가 생긴다면 `lax` 고려해보세요~~

2023-05-02 04:45 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
> +          sameSite: 'none',
프론트와 다른 포트를 사용하게 되면 문제가 발생하군요 감사합니다 ㅎ.ㅎ `lax`로 바꾸겠습니다~

2023-05-02 04:58 UTC, Kimhan-nah commented on backend/src/auth/decorator/auth.decorator.ts
> +  return data ? user?.[data] : user;
해당 decorator를 사용하지 않는 것으로 수정해서 삭제했습니다!

2023-05-02 06:01 UTC, Kimhan-nah commented on backend/src/auth/decorator/auth.decorator.ts
> +  return data ? user?.[data] : user;
라고 했지만 `@Req()` 사용하니까 `LoginInfo`의 id가 항상 null인 문제가 발생하여 data parameter는 없는 decorator로 복구하였습니다

2023-05-02 08:00 UTC, anso33 approved these changes
개인적으로도 길게 물어봤는데 친절한 답변 감사합니다! 덕분에 auth 로직을 얼추 이해하게 되었어요!!
길고 긴 auth 대장정 수고하셨습니다!!! 
굳굳

2023-05-02 08:02 UTC, Kimhan-nah commented on backend/.env.example
> +CALLBACK_URL=
공유하거나 각자 42 intra에서 api 등록하면 됩니닷! 근데 각자하는 게 좋을 것 같아욤!

2023-05-02 08:03 UTC, Kimhan-nah commented on backend/src/auth/auth.service.ts
> +      user.id = auth.id;
로그인을 한 적은 있지만 닉네임을 설정하지 않아 아직 user로 등록되지 않은 경우는 auth table에 존재하지만, 로그인이 완전히 처음이라면 auth table에 존재하지 않아서 추가된 로직입니당 ㅎㅎ

2023-05-02 08:58 UTC, jis-kim approved these changes
구현 사항 모두 확인했습니다! 수고하셨어요!!!!!

2023-05-02 08:59 UTC, Kimhan-nah commented on backend/src/user/user.controller.ts
> +    res.clearCookie('jwt-for-unregistered').redirect(`/auth?token=${token}`);
넵 확인했습니다 ㅎ.ㅎ

2023-05-02 09:00 UTC, merged