✨ [Feature] Apply Guards for user and guest
GhostPangPang/GhostPong pull request #196
Opened 2023-05-05 13:04 UTC by Kimhan-nah

## Summary
- 로그인 관련한 Guard 적용

## Describe your changes
### Guards
- 기존 AuthGuard 수정
  - `AuthGuard('ft')` -> `FtGuard`
  - `AuthGuard('user')` -> `UserGuard`
  - `AuthGuard('auth')` -> `GuestGuard`
- `UserGuard` 전역 가드로 적용
  - development 단계에서 user guard 항상 true return
- UserGuard skip하는 `@SkipUserGuard` 생성

### token에서 userId 반환하는 custom decorator(`@ExtractUserId`)
- `@Headers` 대신 `@ExtractUserId`로 수정
  - 개발 단계에서 사용할 `@Headers`는  `@ExtractUserId`에 내부적으로 추가함

### 테스트
- development 단계에서 token 없어도 테스트 가능한 것 확인 (header에 'x-my-id'로 테스트하기)
![image](https://user-images.githubusercontent.com/33301153/236464721-82e840ed-2813-485b-969b-ddcb2ac056c9.png)

## Issue number and link
- #138

2023-05-05 13:10 UTC, Kimhan-nah reviewed
추가적인 질문 있으면 남겨주세용!

2023-05-05 13:10 UTC, Kimhan-nah commented on backend/src/app.module.ts
> +  providers: [AppService, { provide: APP_GUARD, useClass: UserGuard }],
`UserGuard`를 global-scoped (전역 가드)로 설정했습니다

2023-05-05 13:10 UTC, Kimhan-nah commented on backend/src/auth/auth.module.ts
> +    AppConfigModule,
`clientUrl이` 필요해서 `AppConfigModule` 추가했습니다

2023-05-06 03:40 UTC, anso33 approved these changes
잘 봤습니다.
로그인을 안해봐서 사실 한나님의 코드로 배우는 입장의 리뷰임을 감안해주십사....

2023-05-06 03:40 UTC, anso33 commented on backend/src/common/decorator/extract-user-id.decorator.ts
> +  const request = ctx.switchToHttp().getRequest();
여기가 토큰에서 UserId 추출해주는 부분인가요?

2023-05-06 07:24 UTC, jis-kim requested changes
가드의 달인!!!!! 코멘트 확인 부탁드립니다!!

2023-05-06 07:24 UTC, jis-kim commented on backend/src/auth/auth.controller.ts
>    }
이제 필요없는 test route 같은데 삭제해주실 수 있나요?

2023-05-06 07:24 UTC, jis-kim commented on backend/src/auth/auth.controller.ts
> +      console.log('UNREGISTERED');
`console.log` 삭제해주세요!

2023-05-06 07:24 UTC, jis-kim commented on backend/src/auth/auth.controller.ts
> +      console.log(token);
`console.log` !!

2023-05-06 07:24 UTC, jis-kim commented on backend/src/auth/decorator/extract-user.decorator.ts
> +export const ExtractUser = createParamDecorator((data: unknown, ctx: ExecutionContext) => {
return type 적어주세요!

2023-05-06 07:24 UTC, jis-kim commented on backend/src/auth/guard/user.guard.ts
> +    const skipUserGuard = this.reflector.get<boolean>('skipUserGuard', context.getHandler());
이게 controller (route handler) 에 지정된 `skipUserGuard` 라는 메타데이터를 가져오는 부분인가요??

2023-05-06 07:24 UTC, jis-kim commented on backend/src/auth/strategy/guest.strategy.ts
> +    console.log("Guest strategy's validate");
`console.log`!!!!!!!!

2023-05-06 07:24 UTC, jis-kim commented on backend/src/common/decorator/extract-user-id.decorator.ts
> +    return request.headers['x-my-id'];
요기 `+` 붙여주신다고 했는데 반영가능한가요?

2023-05-06 07:24 UTC, jis-kim commented on backend/src/friend/friend.controller.ts
>      // FIXME: myId 임시 헤더라서 + 갈겼습니다...
요거 빼주실 수 있나요? 헤헷

2023-05-06 07:24 UTC, jis-kim commented on backend/src/user/user.service.ts
> +    // await this.authService.checkExistAuthId(myId); // FIXME : guard
이것도 `GuestGuard` 로 대체되어서 지워도 될 것 같아요!

2023-05-06 07:41 UTC, Kimhan-nah commented on backend/src/common/decorator/extract-user-id.decorator.ts
> +  const request = ctx.switchToHttp().getRequest();
userId를 추출하려면 request가 필요하기 때문에 해당 코드는 request를 반환하는 것입니다!
아래 return에서 request.user.userId를 통해 userID를 반환하게 됩니다!

2023-05-06 07:43 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
>    }
이것은 제가 `guard` 관련해서 테스트할 때 필요한 건데 로그인 관련한 모든 기능들 구현이 끝나면 삭제하도록 하겠습니다!
앞으로 필요할 수 있어서 `FIXME` 주석처리 되어있는 모든 곳은 함께 마지막에 삭제하도록 할게용

2023-05-06 07:43 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
> +      console.log('UNREGISTERED');
앗 넵 알겠습니닷 ㅎ.ㅎ

2023-05-06 07:45 UTC, Kimhan-nah commented on backend/src/friend/friend.controller.ts
>      // FIXME: myId 임시 헤더라서 + 갈겼습니다...
주석 말씀하시는 거죠??

2023-05-06 08:02 UTC, Kimhan-nah commented on backend/src/auth/guard/user.guard.ts
> +    const skipUserGuard = this.reflector.get<boolean>('skipUserGuard', context.getHandler());
맞습니다! GPT 선생님의 설명을 덧붙이자면,
>  skipUserGuard라는 이름의 boolean 타입의 메타데이터 값을 현재 요청 또는 연결 상황에서 실행되는 핸들러(메서드)에서 가져오는 코드입니다. 이 코드를 사용하여, skipUserGuard 메타데이터 값을 true로 설정하여 인증을 건너뛸 수 있도록 설정할 수 있습니다.

라고 합니다 ㅎ.ㅎ

2023-05-06 08:02 UTC, Kimhan-nah commented on backend/src/common/decorator/extract-user-id.decorator.ts
> +    return request.headers['x-my-id'];
넵 알겠습니다!

2023-05-06 08:04 UTC, Kimhan-nah commented on backend/src/friend/friend.controller.ts
>      // FIXME: myId 임시 헤더라서 + 갈겼습니다...
지웟씁니다!

2023-05-06 08:16 UTC, jis-kim approved these changes
확인했습니다. 고생많으셨어요~~

2023-05-06 08:45 UTC, merged