✨ [Feature] scrollable layout
GhostPangPang/GhostPong pull request #225
Opened 2023-05-09 04:33 UTC by aLVINlEE9

## Summary
스크롤 가능한 레이아웃 제작

## Describe your changes

- [ ] 스크롤 가능한 레이아웃 제작
- [ ] footer 제작
- [ ] 레이아웃에 맞게 profile page 수정

## Issue number and link

2023-05-09 05:34 UTC, nyeoni requested changes

2023-05-09 05:34 UTC, nyeoni commented on frontend/src/layout/ScrollableLayout/ScrollableHeader.tsx
> +export const ScrollableHeader = ({ nickname, image, exp, items }: ScrollableHeaderProps) => {
기존 `Header` 를 쓰면 안되나요?? 만약에 일부 속성만 바뀌어야 한다면 기존 `Header` 에 프로퍼티를 추가하여 사용하는건 어떨까요?

2023-05-10 06:22 UTC, nyeoni commented on frontend/src/layout/Header/Header.tsx
> +  Pick<ResponsiveProps, 'xs'>;
`xs` 를 추가 했으면, `md` 랑 `lg` 도 추가하면 좋을 것 같아요!

2023-05-10 06:22 UTC, nyeoni commented on frontend/src/layout/MainLayout/MainLayout.tsx
> +      <Header
`Header` 내부에서 useAuth 를 받는게 좋을 것 같아요!

2023-05-10 06:23 UTC, nyeoni approved these changes
고생많으셨습니다 :) 굳굳!!

2023-05-10 06:23 UTC, aLVINlEE9 commented on frontend/src/layout/MainLayout/MainLayout.tsx
> +      <Header
이 부분은 Header api 연결 이슈(https://github.com/GhostPangPang/GhostPong/issues/235)로 빼두었습니다

2023-05-10 06:28 UTC, merged