✨ [Feature] Edit profile page api connection
GhostPangPang/GhostPong pull request #263
Opened 2023-05-10 16:45 UTC by aLVINlEE9

## Summary
Edit page api 연결을 하였습니다. ( 2FA는 벡엔드 마무리 되는 대로 작업 이어서 하겠습니다)

## Describe your changes

- [ ] 프로필 사진 변경
- [ ] 닉네임 변경
- [ ] 2FA 설정

## Issue number and link

- [ ] https://github.com/GhostPangPang/GhostPong/issues/210

2023-05-13 11:53 UTC, nyeoni commented on frontend/src/common/InputBox/InputBox.tsx
> +  display?: string;
왜 `display` 속성을 추가하셨나요?

2023-05-13 11:56 UTC, nyeoni commented on frontend/src/hooks/useFileUpload.tsx
> +        alert('프로필 사진이 변경되었습니다.');
patch 나 post 된 api 요청은 `res.data.message` 에서 온대로 띄워주시면 더 좋을 것 같습니다.

2023-05-13 12:14 UTC, nyeoni commented on .DS_Store
이게 뭐죠?ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-05-13 12:19 UTC, nyeoni requested changes
코멘트 확인해주세요! :)

2023-05-13 12:19 UTC, nyeoni commented on frontend/src/pages/EditProfilePage/UploadFile/UploadFile.tsx
> +export const UploadFile = ({ handleFileChange }: UploadFileProps) => {
`onChange` 로 받으면 좋겠습니다 :) 저희가 오늘 정한 컨벤션에 따라서!!ㅎㅎ

2023-05-13 12:34 UTC, aLVINlEE9 commented on frontend/src/pages/EditProfilePage/UploadFile/UploadFile.tsx
> +export const UploadFile = ({ handleFileChange }: UploadFileProps) => {
네 좋아요!

2023-05-13 13:07 UTC, aLVINlEE9 commented on frontend/src/common/InputBox/InputBox.tsx
> +  display?: string;
..그러게요 지우겠습니다

2023-05-15 05:18 UTC, nyeoni commented on frontend/src/hooks/usePatchNickName.tsx
> +        Promise.reject(new Error(error.message));
여기서는 왜 return 을 안하신거죠?ㅋㅋㅋㅋㅋㅋ

2023-05-15 05:18 UTC, nyeoni approved these changes
굳굳 오랜시간 고생많으셨습니다 :) 뷰 너무 이쁘네요 >_<

2023-05-15 05:26 UTC, aLVINlEE9 commented on frontend/src/hooks/usePatchNickName.tsx
> +        Promise.reject(new Error(error.message));
아... 빨리 고치겠습니다

2023-05-15 05:56 UTC, merged