:hammer: [Refactor] Add createdAt, receiverId in messageDto
GhostPangPang/GhostPong pull request #304
Opened 2023-05-13 12:34 UTC by anso33

## Summary
- `createdAt`, `receiverId`를 `messageDto` 및 message `type`에 추가했습니다.
- `receiverId`를 이용해서 socketId로 보내는 로직 구성했습니다.
- dto로 받은 `createdAt`으로 message entity를 db에 저장합니다.

## Describe your changes
- `createdAt` : 페이지 구성할 때 필요하다는 요청 발생하여 추가했습니다. 
- `receiverId` : 클라이언트에서 보내줄 수 있고 해당 값이 있으면 서버에서 socket room을 만들지 않아도 됨, room으로 인해 생겼던 event 삭제 가능해서 반영했습니다. 

- 친구 관계로 socket room을 만들어 메세지를 보내는 로직이 삭제되면서 dto의 친구 관계 아이디의 유효성을 검사해야하나 고민했는데요.
`friendId`의 유효성을 검사한다면 고려해야할 점이 2가지 있다고 생각했습니다. 
1. blocked 되어서 메세지 씹혀야 하는 경우
2. 그냥 유효하지 않은 친구인 경우 
`1`에 대해서는 프론트에서 blocked 리스트 가지고 있어서 그냥 이벤트 받아서 잘 처리해주기로 해서 고려하지 않아도 됩니다.  
그럼 `2`가 남는데 소켓 통신이니까 빠르게 동작하는 걸 멈출만큼 필요한가 를 중점으로 생각했습니다. db를 다녀오려면 `await`를 거니까요. 그런데 어차피 이 이벤트를 발생할 때는 프론트에서 메세지 페이지에서 가지고 있는 친구데이터로 `friendId`를 넣어서 event 보내게 됩니다. 즉, 정상적인 `ui`로 동작시켰다면 일어나지 않을 일인거죠! 유효하지않은 값을 넣어서 보내려면 소켓 `connect`시 부터 `access token`이 털린 경우이므로 db까지 다녀올 필요가 없다고 생각해서 넣지 않았습니다!! 

## Issue number and link
- close #299

2023-05-13 14:19 UTC, Kimhan-nah approved these changes
확인했습니다아

2023-05-13 14:19 UTC, Kimhan-nah commented on backend/src/message/dto/socket/message.dto.ts
> +  createdAt: Date | string;
타입이 왜 둘다 가능한 거예용??

2023-05-14 01:20 UTC, jis-kim requested changes
코멘트 남겼습니다! pr에서 db 확인 안하신 이유 보고 생각해봤는데 어차피 `message` 테이블에 값을 넣어주는 소켓통신이기 때문에 `await` 은 걸리고 `friendship` 테이블에서 `findOndBy` 한 번 한다고 크게 차이가 날 것 같지 않습니다. http 요청들에서는 access 토큰을 탈취당했을 경우 비슷한 검증을 모두 해주는데 해당 부분만 생략하는 것은 보안 및 일관성이 낮은 방식이라고 생각됩니다.

2023-05-14 01:20 UTC, jis-kim commented on backend/src/message/message.gateway.ts
> +      return; //TODO: exception handling
요기는 에러 핸들링 안하고 그냥 `return`하면 될 것 같아요. 그냥 친구가 접속 중이지 않은 상태이기 때문입니다!

2023-05-14 01:20 UTC, jis-kim commented on backend/src/message/dto/socket/message.dto.ts
> +  @IsNumber()
이거 `@Length(min, max)` 로 바꾸고 `@IsNotEmpty` 없앨 수 있을까요?ㅎㅎ 위의 `senderId` 에도 적용해주세요

2023-05-14 01:20 UTC, jis-kim commented on backend/src/message/dto/socket/message.dto.ts
> +  createdAt: Date | string;
급 대신 답변...! client 가 받을 때는 해당 타입이 `string` 이고 server 가 넣을 때는 `Date` 형식이라서 현대 날짜 형태의 모든 dto가 유니온 타입입니다. 이거 다른 방법이 없을까 고민해봐야 하는데 흠... 일단 이러면 스펙에 맞게 돌아는 갑니다!!

2023-05-14 01:22 UTC, jis-kim commented on backend/src/message/message.gateway.ts
> +    await this.messageRepository.insert({
이 부분 이전에 `friendId` 로 `friendship`을 찾아서 `sender` 및 `receiver` 가 친구관계 구성원과 일치하는지 확인하는 로직이 있어야 한다고 생각합니다.

2023-05-14 02:13 UTC, anso33 commented on backend/src/message/message.gateway.ts
> +    await this.messageRepository.insert({
음 일단 유효하지 않은 관계로 보내도 메세지가 저장이 되고 상대방에게 message event가 가긴 한다는 게 이상하다고는 생각했는데요. 뭐 챗 선생님이랑도 

> 보안과 데이터 일관성을 위해서는 유효성 검사를 수행하는 것이 좋습니다. 소켓 통신이더라도 데이터의 무결성을 유지하기 위해 검사를 해야합니다.
소켓 통신은 클라이언트와 서버 간의 실시간 데이터 교환을 위한 매우 효율적인 방법이지만, 클라이언트에서 서버로 전송되는 데이터의 유효성을 검사하지 않으면 데이터의 정확성과 안전성이 보장되지 않을 수 있습니다. 

이라는 의견이 있고.......  그래서 친구 관계의 유효성을 따지는 로직을 추가하겠습니다.

2023-05-14 02:14 UTC, anso33 commented on backend/src/message/message.gateway.ts
> +    await this.messageRepository.insert({
우선은 이 브랜치가 끝나야 프론트가 작업하기 수월해서 디비가서 확인하는 방법으로 수정하겠습니다.

2023-05-14 02:22 UTC, anso33 commented on backend/src/message/message.gateway.ts
> +    await this.messageRepository.insert({
그런데 서버 내에서 유효성 검사를 어떻게 진행할지 한번 더 생각해보는 것도 좋을 것 같아요.
1. 메세지 보낼 때마다 DB가서 확인한다. 
- 장: 친구 관계가 변경(친구 끊거나 block)될 때 따로 처리할 필요 없이 그냥 DB가서 확인하면 실시간으로 반영받을 수 있다. 
- 단: 메세지 보낼때마다 db 두 번 간다. 

2. 처음처럼 `friend-$(friendId)`로 소켓 `room`을 만들어서 `room`으로 이벤트 전달한다. 
- 장: 친구 관계 유효성을 `room`만들때 이미 다 처리해놔서 그냥 보내고 message 저장만 하면 되어서 메세지 실시간 통신은 빠르다. 
- 단: 친구 관계가 변경될때 `room`에 따로 처리를 해주는 작업을 추가해야한다. . (room을 나간다던지.)
       사실 어차피 메세지 저장으로 DB한번은 간다. 
       유저가 많아지면 서버 자원을 고려해야한다. 
       
오 이렇게 적고 보니까 1번으로 완전 마음이 기우네요ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
2번 방법 별로인거 같아요!!ㅋㅋㅋㅋㅋ
그래도 다른 분들 의견도 물어봅니다. @Kimhan-nah @jis-kim

2023-05-14 02:35 UTC, anso33 commented on backend/src/message/dto/socket/message.dto.ts
> +  @IsNumber()
@Length(1, 2147483647)

이거 말씀하신건가요?

2023-05-14 02:36 UTC, anso33 commented on backend/src/message/dto/socket/message.dto.ts
> +  @IsNumber()
아니아니 오잉 이건 문자열 길이 체크 하는거 아닌가요?

2023-05-14 02:43 UTC, jis-kim commented on backend/src/message/dto/socket/message.dto.ts
> +  @IsNumber()
아그렇네요?!ㅋㅋㅋ 쏴리쏴리걸.... 취소합니다

2023-05-14 02:44 UTC, jis-kim commented on backend/src/message/message.gateway.ts
> +    await this.messageRepository.insert({
저도 1번이 맞다고 생각합니다!

2023-05-14 03:46 UTC, Kimhan-nah commented on backend/src/message/message.gateway.ts
> +    await this.messageRepository.insert({
좋습니다..! 1번 고고!

2023-05-14 04:43 UTC, anso33 commented
반영했는데요//... 아직 타스에 약해서 그런데.....ㅋㅋㅋㅋ 혹시 `checkExistFriendShip의 조건문을 줄일 수 있는 방법을 아신다면 조언해주시겠습니까?

2023-05-14 04:48 UTC, Kimhan-nah commented on backend/src/user/dto/response/user-nickname-response.dto.ts
`user-nickname-response` 관련한 파일들 삭제하는 거 hotfix로 빼서 이미 main에 합쳐져 있어요!

2023-05-14 04:55 UTC, anso33 commented on backend/src/user/dto/response/user-nickname-response.dto.ts
ㅋㅋㅋㅋㅋpush를 제가 잘못했네요
수정했습니다.

2023-05-14 05:01 UTC, Kimhan-nah reviewed
확인 부탁드립니다아

2023-05-14 05:01 UTC, Kimhan-nah commented on backend/src/message/message.gateway.ts
> +  }
```suggestion
    const friendship = await this.friendshipRepository.findOneBy([
      { senderId: senderId, receiverId: receiverId }, // sender -> receiver
      { senderId: receiverId, receiverId: senderId }, // receiver -> sender
    ]);
      if (friendship === null || friendship.id !== friendId || friendship.accept !== true) {
      throw new Error('유효하지 않은 친구 관계입니다.');
      }
```

어떠신가용??

2023-05-14 06:39 UTC, anso33 commented on backend/src/message/message.gateway.ts
> +  }
이거 고려했었는데 `pk`만 사용한 단일조건으로 `select`하고 얻어온 값으로 직접 나머지 `value`를 비교하면 유효성 검사가 더 빨리 동작하지 않을까 라는 생각으로 이렇게 작성했습니다! 근데 실제로 어떻게 비교해야할 지몰라서 정말 얼마나 차이나는지는 모르겠어요..ㅠㅜ

2023-05-14 07:54 UTC, Kimhan-nah commented on backend/src/message/message.gateway.ts
> +  }
```suggestion
    const friendship = await this.friendshipRespository.findOneBy([
  { id: friendId, senderId: senderId, receiverId: receiverId, accept: true },
  { id: friendId, senderId: receiverId, receiverId: senderId, accept: true },
]);
    if (friendship === null) {
      throw new Error('존재하지 않는 친구 관계입니다.');
    }
    if (
      (friendship.senderId === senderId && friendship.receiverId === receiverId && friendship.accept === true) ||
      (friendship.senderId === receiverId && friendship.receiverId === senderId && friendship.accept === true)
    ) {
      return;
    }
    throw new Error('유효하지 않은 친구 관계입니다.');
  }
```

로 하는 건 더 오래 걸리나요?? 이렇게하면 완전 간단해질 거 같긴한데..ㅎㅎ

2023-05-14 07:58 UTC, Kimhan-nah commented on backend/src/message/message.gateway.ts
> +  }
는 오래 걸릴 것 같군요..ㅎ

2023-05-14 08:00 UTC, Kimhan-nah commented on backend/src/message/message.gateway.ts
> +  }
속도를 고려해서 id로 찾는 방법으로 진행하신다면 이대로 갈 수 밖에 없겠는데요??

2023-05-15 03:19 UTC, jis-kim approved these changes
수장사항 반영 완료된 것 확인했습니다!바로 머지하겠습니다 수고하셨어요~

2023-05-15 03:19 UTC, jis-kim commented on backend/src/message/message.gateway.ts
> +      (friendship.senderId === senderId && friendship.receiverId === receiverId && friendship.accept === true) ||
if문을 깔끔하게 하는 방법은 `friendship` 구성원인지 확인하는 이 부분을 함수로 빼는 방법밖에 생각나지 않네요..

2023-05-15 03:19 UTC, merged