✨ [Feature] Feature socket-event for chatting
GhostPangPang/GhostPong pull request #334
Opened 2023-05-18 13:13 UTC by anso33

## Summary
채널에서 채팅하는 이벤트 추가했습니다. 

## Describe your changes
- `mute` 된 유저이면 `ACK`으로 응답합니다. 
- 없는 채널이거나, 없는 유저이면 `WsException`을 반환합니다. 

## Issue number and link
- close #332

2023-05-18 13:41 UTC, jis-kim requested changes
코멘트 확인 부탁드립니다~~! ack 처리 좋아욥

2023-05-18 13:41 UTC, jis-kim commented on backend/src/channel/channel.gateway.spec.ts
spec 파일 안쓰시면 지워서 올려주세요!

2023-05-18 13:41 UTC, jis-kim commented on backend/src/channel/channel.gateway.ts
> +    const channel = this.channelRepository.find(data.channelId);
요거 `privateChannelRepository` 에서도 찾아서 보내줘야 합니다!

2023-05-18 13:41 UTC, jis-kim commented on backend/src/channel/channel.gateway.ts
> +    const channel = this.channelRepository.find(data.channelId);
private 만 저장되어있는 레포지토리고 그냥 `channelRepository` 에는 public, protected 가 있어서 둘 다에서 찾아줘야해요

2023-05-18 13:41 UTC, jis-kim commented on backend/src/channel/channel.gateway.ts
> +      return '당신은 뮤트된 유저입니다.';
이거 뭔가 객체로 안보내고 그냥 string 으로 ack 하시나요? 다 객체 형식인데 얘만 이래서 여쭤봅니다.

2023-05-19 01:47 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +    const channel = this.channelRepository.find(data.channelId);
ㅎㅎㅎㅎㅎㅎㅎㅎprivate 따로 저장하고 있는 걸 잊어먹었네염ㅎㅎㅎ

2023-05-19 02:41 UTC, Kimhan-nah reviewed
pipe merge 되었으니 사용하시면 될 거 같아요!

2023-05-19 02:41 UTC, Kimhan-nah commented on backend/src/channel/channel.gateway.ts
> +    const channel = this.channelRepository.find(data.channelId);
`private` channel을 제외한 나머지 channel에 대해 존재하는 지 검증하는 `CheckChannelIdPipe`를 만들었습니다! merge 되어서 반영되었는데 해당 pipe를  gateway에서도 적용가능 한 걸로 알고있어유 고거 사용하시면 될듯!!

2023-05-19 02:41 UTC, Kimhan-nah commented on backend/src/channel/channel.gateway.ts
> +    const channel = this.channelRepository.find(data.channelId);
추가로 `private` channel도 존재하는 지 검증하는 pipe를 만들까요 ? 생각해보니 private 방 참여에 대해서 생각을 못했는데.. 이건 같이 좀더 얘기해보아용

2023-05-19 05:35 UTC, Kimhan-nah commented on backend/src/channel/channel.module.ts
> +    CacheModule.register({ store: 'memory', ttl: 1000 * 60 }),
mute 시간이 1000 * 60 (1분)인 거 같은데 constant로 따로 뺄까용??

2023-05-19 05:51 UTC, Kimhan-nah commented on backend/src/channel/channel.gateway.ts
> +    if ((await this.cacheManager.get(`${data.senderId}`)) !== undefined) {
저희 `cacheManage`를 같이 사용해야돼서 key 값 겹치지 않도록 같이 얘기해보고 수정해야될 거 같아요 ㅠ.ㅠ

2023-05-19 09:25 UTC, anso33 commented on backend/src/channel/channel.module.ts
> +    CacheModule.register({ store: 'memory', ttl: 1000 * 60 }),
constant로 빼면 장점이 뭔가요????

2023-05-19 09:26 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +    if ((await this.cacheManager.get(`${data.senderId}`)) !== undefined) {
오 이거 물어보고 싶었는데 제가 좀 더 찾아보고 말씀 드릴게염

2023-05-19 10:01 UTC, Kimhan-nah commented on backend/src/channel/channel.module.ts
> +    CacheModule.register({ store: 'memory', ttl: 1000 * 60 }),
가독성과... 확장성과.. 유지보수...? 
지금은 여기밖에 사용 안할 수도 있긴한데 약간 c에서 매크로 define해서 'MAX_' 이런 느낌이지 않을까요??

2023-05-20 06:55 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +      return '당신은 뮤트된 유저입니다.';
프론트와 이야기 한 결과 똑같이 
```
{message: '뮤트되었습니다.'}
```
로 보내겠습니다

2023-05-20 06:56 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +    if ((await this.cacheManager.get(`${data.senderId}`)) !== undefined) {
`mute-${data.senderId}` 로 키값 사용하겠습니다!

2023-05-20 08:41 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +    const channel = this.channelRepository.find(data.channelId);
pipe 적용을 위한 비용 대비 시간이 적어서 파이프 적용은 나중에 생각하는 걸로 결론 내렸습니다! 대신 로직을 분리했습니다

2023-05-20 08:42 UTC, anso33 commented
리뷰 해주쎄용! @Kimhan-nah @jis-kim

2023-05-20 08:55 UTC, jis-kim reviewed
수고하셨어요~ 코멘트확인 부탁드립니다~~

2023-05-20 08:55 UTC, jis-kim commented on types/channel/socket/index.ts
> +export { Chat } from './chat.interface';
요거 우리 다 `import *` 으로 바뀌었는데잉!!! 하지만 상관없습니다 ㅎㅎ

2023-05-20 08:55 UTC, jis-kim commented on backend/src/common/constant.ts
> +const MUTE_EXPIRES_IN = 1000 * 60;
`MUTE_OVER` 어떠세요.? 아님 `MUTE_END_TIME` ?

2023-05-20 08:55 UTC, jis-kim commented on backend/src/channel/channel.gateway.ts
> +  logger: Logger = new Logger('ChannelGateway');
혹시 logger 를 어디서 쓰고 계시는 걸까요?? 그냥 선언하신 건가요?

2023-05-20 08:55 UTC, jis-kim commented on backend/src/channel/channel.gateway.ts
> +    }),
흠 저희 이거 너무 많이 쓰이는데 그냥 `common/util.ts` 만들고 함수로 빼서 이름만 쓸까요?

2023-05-20 08:55 UTC, jis-kim commented on backend/src/channel/channel.gateway.ts
> +    }
로직상 여기를 먼저 체크해야 하지 않을까요? 해당 방에 참여하지 않은 유저인데 다른 방에서 뮤트되었을 경우 "뮤트된 유저입니다" 가 답으로 갈 것 같아요

2023-05-20 08:55 UTC, jis-kim commented on backend/src/channel/channel.gateway.ts
> +    }
이거 `socket.data.userId` 를 그냥 `broadcast` 하실 때 포함시켜서 주면 `ChatDto` 에 `senderId` 가 필요없는데 삭제하는 것 제안드립니다!

2023-05-20 08:55 UTC, jis-kim commented on backend/src/channel/channel.gateway.ts
> +      if ((channel = this.invisibleChannelRepository.find(channelId)) === undefined) {
이거 `&&` 해주세요~~

2023-05-20 08:56 UTC, anso33 commented on types/channel/socket/index.ts
> +export { Chat } from './chat.interface';
옷 요거 반영하겠습니다.

2023-05-20 08:58 UTC, anso33 commented on backend/src/common/constant.ts
> +const MUTE_EXPIRES_IN = 1000 * 60;
오 근데 캐시 매니저를 사용하는 다른 값들은 `EXPIRES_IN` 를 사용하는데 `MUTE_EXPIRES_IN`으로 하는게 통일성 있을 것 같아요!

2023-05-20 08:59 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +  logger: Logger = new Logger('ChannelGateway');
test용 event 코드에서 썼었는데 앞으로 Channel gateway 구현하면서 쓸일이 있을 것 같아서 남겨두겠습니다!

2023-05-20 09:05 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +    }
구성한 channel 정책상 하나의 `Room`에만 join될 수 있는데요. 그래서 mute된 유저면 어차피 메세지를 못 보내는데  mute를 마지막에 검사하면 불필요한 Channel에 대한 검사를  하게 되지 않나라는 생각으로 Mute를 가장 먼저 검사했습니다. 어떻게 생각하세요???

2023-05-20 09:07 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +    }
API 양식상 들어오고 나가는 dto가 다르면 이벤트 분리하기로 했는데 chat이벤트의 경우 그것보다는 하나의 이벤트로 처리하고 dto 통일, senderId 검사(비용이 많이 드는 로직이 아님)하는것이 나을 것 같습니다.

2023-05-20 09:07 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +      if ((channel = this.invisibleChannelRepository.find(channelId)) === undefined) {
조아염~

2023-05-20 09:11 UTC, jis-kim commented on backend/src/channel/channel.gateway.ts
> +    }
으으음 그러게요 제가 말한 게 일어날 일이 거의 없는 경우고 뮤트는 빈번하게 일어나니까 뮤트를 먼저 체크하는 게 맞는 것 같아 보입니다!! 좋습니당

2023-05-20 09:30 UTC, anso33 commented on backend/src/channel/channel.gateway.ts
> +    }),
i do that! ><

2023-05-20 09:33 UTC, anso33 commented
고쳤어염!!ㅎㅎㅎ

2023-05-20 09:48 UTC, jis-kim approved these changes
확인했습니다. 수고하셨어요!!!!!

2023-05-20 09:48 UTC, jis-kim approved these changes
확인했습니다. 수고하셨어요!!!!!

2023-05-20 10:01 UTC, Kimhan-nah approved these changes
확인했습니당

2023-05-20 10:01 UTC, anso33 commented
감사합니당! 42!

2023-05-20 10:02 UTC, merged