✨ [Feature] Update channel information
GhostPangPang/GhostPong pull request #430
Opened 2023-05-25 08:51 UTC by Kimhan-nah

## Summary
- channel 정보 변경

## Describe your changes
- update 성공하면 `channel-updated` socket event broadcast

### Test
<img width="395" alt="스크린샷 2023-05-25 오후 5 50 24" src="https://github.com/GhostPangPang/GhostPong/assets/33301153/54eafc16-6016-4aef-b42b-76d720873c0a">

## Issue number and link
- close #364

2023-05-25 13:05 UTC, jis-kim requested changes
수고하셨습니다! 코멘트를 남겼습니다~~ 채널은 항상 헷갈리네요...

2023-05-25 13:05 UTC, jis-kim commented on backend/src/channel/channel.service.ts
> +    channel.mode = updateChannelOptions.mode;
여기 `channel` 이 reference 인 점을 활용해서 바로 수정하신 것 같은데 이러시면 public, protected -> private 으로 수정하거나 private -> public, protected 로 수정하였을 때 레포지토리 간 이동이 되지 않습니다...! 기존 `channel` 의 `mode` 를 확인해서 레포지토리를 다시 정해주든지 업데이트 하든지 해야 할 것 같습니다.

2023-05-26 02:59 UTC, Kimhan-nah commented on backend/src/channel/channel.service.spec.ts
> +    });
넵 추가했습니다!

2023-05-26 03:51 UTC, anso33 approved these changes
확인했습니다ㅏ!~!

2023-05-26 05:06 UTC, jis-kim approved these changes
변경사항 확인했습니다! 수고하셨습니다~

2023-05-26 05:35 UTC, merged