✨ [Feature] get user-meta-info api
GhostPangPang/GhostPong pull request #70
Opened 2023-04-14 17:57 UTC by anso33

## Summary
- 로그인한 유저의 메타데이터 가져오는 API 구현

## Describe your changes
- `GET /user` api 구현
- typeORM 어렵네요... 일단 양식에 맞춰 blockedUser의 id, 즉 숫자 배열만 주기 위해서 QueryBuilder로 뽑은 엔티티에서 다시 필요한 id만 뽑아내는 로직을 넣었습니다. 만일 blocked 한 user가 없다면 빈배열을 주도록 의도했습니다. repository 제공 메서드이던 QueryBuilder이던 원하는 컬럼값만 예쁘게 뽑고 싶었는데 뭐로하던 객체로 한번 감싸서 나오더라구요....만일 원하는 컬러만 예쁘게 뽑아내는 법을 아신다면 제발 알려줍쇼....

- 아 그리고 편의를 위해 test용 db data를 넣는 sql문을 test-data.sql에 넣어놨습니다. 앞으로도 추가할 예정입니다. 참고하십쇼들!!!

## Issue number and link
close #61

2023-04-15 01:58 UTC, jis-kim requested changes
수고하셨습니다. 코멘트 확인 부탁드립니다!

2023-04-15 01:58 UTC, jis-kim commented on backend/src/user/user.controller.ts
> +  @HttpCode(HttpStatus.OK)
`Get()` 의 기본 response status 가 OK 이기 때문에 불필요한 데코레이터 같습니다!

2023-04-15 01:58 UTC, jis-kim commented on backend/src/user/user.module.ts
> +  imports: [TypeOrmModule.forFeature([User, BlockedUser])],
이거 저는 `User` 사용할 때 `Auth` 도 선언하지 않으면 에러가 나던데 (`User.id` 가 `Auth` 에 종속되기 때문에) 실행이 잘 되시던가요..? 아니면 혹시 `databaseConfig` 의 `synchronize` 옵션 을 끄고 실행하셨나요?
<img width="1166" alt="Screenshot 2023-04-15 at 10 31 46 AM" src="https://user-images.githubusercontent.com/71019735/232176761-c1a1fc8a-729d-4a15-9d22-5f6f5a37fd56.png">

2023-04-15 01:58 UTC, jis-kim commented on backend/src/user/user.module.ts
> +  imports: [TypeOrmModule.forFeature([User, BlockedUser])],
아 근데 제가 `friendModule` 에서 `Auth` 를 넣어놔서 괜찮을 수도 있겠네요..! 이 가정이 맞다면 나중에 `AuthModule` 완성되면 필요없는 코드 빼겠습니다.

2023-04-15 01:58 UTC, jis-kim commented on backend/src/user/user.controller.ts
> +  requestMetaInfo(@Headers('x-my-id') myId: number): Promise<MetaInfoResponseDto> {
메소드명으로 `getUserMetaInfo` 제안합니다. 신청하는 api 가 아닌데 request 라는 이름이 붙으면 의미가 불분명한 것 같습니다!

2023-04-15 01:58 UTC, jis-kim commented on backend/src/user/user.service.ts
> +  async requestMetaInfo(myId: number): Promise<MetaInfoResponseDto> {
요것도 controller 에서 말한 것과 같이 함수명이 더 정확한 쪽으로 수정되었으면 합니다..!

2023-04-15 01:58 UTC, jis-kim commented on backend/src/user/user.service.ts
> +  async findMetaInfoById(userId: number): Promise<User> {
여긴 굳이 MetaInfo 보단 `findUserById` 가 나을 것 같습니다. 다른 서비스 함수에서도 쓸 것 같아서 좀 더 제너럴한 네이밍이 좋을 것 같아용

2023-04-15 01:58 UTC, jis-kim commented on backend/src/user/user.service.ts
> +      blockedList.forEach((BlockedUser) => numbers.push(BlockedUser.blockedUserId));
`forEach` 대신 `map` 으로 배열을 바로 리턴할 수 있습니다. 
[참고](https://codeburst.io/javascript-map-vs-foreach-f38111822c0f)

2023-04-15 01:58 UTC, jis-kim commented on backend/src/user/user.service.ts
> +    const blockedList = await this.blockedUserRepository
이 부분은 `createQueryBuilder` 하지 않고 repository 로 해결되지 않을까요? 그냥 userId 로 where 을 주고 selecte는 blockedUserId 하면 될 것 같습니다.

2023-04-15 01:58 UTC, jis-kim commented on backend/src/user/user.service.ts
> +      blockedList.forEach((BlockedUser) => numbers.push(BlockedUser.blockedUserId));
위에서 select 를 `blockedUserId` 만 하면 되는 부분을 왜 전체 `BlockedUser` (Entity) 에서 가공하는 방식으로 하신지도 의문이 드는데 혹시 제가 놓친 부분이 있다면 자세한 설명 부탁드립니다..!

2023-04-15 02:07 UTC, jis-kim commented on backend/src/user/user.controller.ts
> +@Controller('user')
앗 요 위에 `@ApiTags('user')` 도 추가해주세요!

2023-04-15 02:11 UTC, jis-kim commented on backend/src/user/user.service.ts
> +      blockedList.forEach((BlockedUser) => numbers.push(BlockedUser.blockedUserId));
아 ㅎ 갑자기 깨달았는데 제가 friendship 에서 sender 만 뽑을 수 없었던 것과 비슷한 경우네요...?ㅋㅋㅋㅋㅋㅋㅋㅋ 그래도 QueryBuilder -> Repository, forEach -> map 수정 부탁드려요...ㅎㅎ!

2023-04-15 06:16 UTC, anso33 commented on backend/src/user/user.module.ts
> +  imports: [TypeOrmModule.forFeature([User, BlockedUser])],
synchronize 옵션 켜져있었고 지수님 의견대로 싱글톤이라서 가능했던 것 같네염!!

2023-04-15 06:26 UTC, anso33 commented on backend/src/user/user.controller.ts
> +  requestMetaInfo(@Headers('x-my-id') myId: number): Promise<MetaInfoResponseDto> {
아 인정합니다 request 이상했어요ㅋㅎㅋㅋ

2023-04-15 06:27 UTC, anso33 commented on backend/src/user/user.service.ts
> +  async requestMetaInfo(myId: number): Promise<MetaInfoResponseDto> {
화긴!

2023-04-15 06:28 UTC, anso33 commented on backend/src/user/user.service.ts
> +  async findMetaInfoById(userId: number): Promise<User> {
ㅋㅋㅋㅋ네이밍에 신경 좀 많이 쓰겠습니다!

2023-04-15 06:55 UTC, anso33 commented on backend/src/user/user.service.ts
> +      blockedList.forEach((BlockedUser) => numbers.push(BlockedUser.blockedUserId));
화긴!

2023-04-15 06:56 UTC, anso33 commented on backend/src/user/user.controller.ts
> +@Controller('user')
화긴!

2023-04-15 07:30 UTC, Kimhan-nah approved these changes
확인했습니다 고생하셨습니당

2023-04-15 07:35 UTC, jis-kim approved these changes
변경 사항 모두 확인했습니다!! 수고하셨어요~~~~ approve 를 드립니다

2023-04-15 07:54 UTC, merged

2023-04-16 12:34 UTC, Devdha commented on backend/src/user/user.service.ts
> +  }
> QueryBuilder이던 원하는 컬럼값만 예쁘게 뽑고 싶었는데 뭐로하던 객체로 한번 감싸서 나오더라구요....만일 원하는 컬러만 예쁘게 뽑아내는 법을 아신다면 제발 알려줍쇼....

이 부분 말씀하신 것 같은데, queryBuilder로 원하는 컬럼 select 하면 됩니다!

여기서는 아래와 같이 해보면 될 것 같아요!
디비에서 select 해서 가져오면 아무래도 성능이나 메모리 적으로 이점이 있을 것 같네요!
```
this.blockedUserRepository
        .createQueryBuilder()
        .select('blockedUserId')
        .getRawMany();

// 반환은 이런 형태로 예상됩니다. -> [ {blockedUserId: (id)}, {}... ] 
```

2023-04-16 13:23 UTC, anso33 commented on backend/src/user/user.service.ts
> +  }
오 근데 객체 둘러져나온다고 다시 repository로 바꾸긴 했는데 dha님 말씀대로 원하는 컬럼만 가져온다는 걸로도 충분히 의미가 있는 사용일 것 같네요!!! .map은 어쩔 수 없지만ㅠㅜㅠㅜㅠ 

아니 이 황금 일요일에 comment를.... 감사하므니다ㅠㅜㅠㅜㅠㅜ
월요일 잘 견디십쇼!!!!!

2023-04-16 14:13 UTC, Devdha commented on backend/src/user/user.service.ts
> +  }
감사합니다~ 트센 파이팅이에요!! 😆