✨ [Feature] create nickname API (create new user)
GhostPangPang/GhostPong pull request #76
Opened 2023-04-15 11:53 UTC by Kimhan-nah

## Summary

## Describe your changes

## Issue number and link

2023-04-15 12:23 UTC, jis-kim requested changes
변경사항 적용 부탁드립니다 : ] 수고하셨어요!!

2023-04-15 12:23 UTC, jis-kim commented on backend/src/auth/auth.service.ts
> +    if (await this.authRepository.findOneBy({ id: authId })) {
요거 if문 로직이 반대인 것 같습니다. `findOneBy` 의 리턴이 null 일 때로 조건을 바꿔주세요!

2023-04-15 12:23 UTC, jis-kim commented on backend/src/common/constant.ts
> +export const DEFAULT_IMAGE = 'default image';
요거 그래도... url 같아보이는 걸로 해주세용 ㅎㅎ

2023-04-15 12:23 UTC, jis-kim commented on backend/src/auth/dto/nickname-request.dto.ts
> +  @MaxLength(8)
dto 에도 주석으로 swagger 정보 달 수 있으니까 추가해주세요!!

2023-04-15 21:12 UTC, anso33 reviewed
지수님이 너무 잘 달아주셔서 더 달게 없네유!! 고생하셨습니다!!!!

2023-04-15 21:12 UTC, anso33 commented on backend/src/auth/dto/nickname-success-response.dto.ts
> +export class NicknameSuccessResponseDto {
요기 닉네임 설정 responsedto라는게 잘 드러나게 바꾸면 좋지 않을까욥! (success 빼고)

2023-04-16 01:52 UTC, Kimhan-nah commented on backend/src/auth/dto/nickname-success-response.dto.ts
> +export class NicknameSuccessResponseDto {
변경 완료했습니

2023-04-16 01:53 UTC, Kimhan-nah commented on backend/src/auth/dto/nickname-request.dto.ts
> +  @MaxLength(8)
넵 추가 완료했습니당

2023-04-16 01:55 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
> +  @ApiNotFoundResponse({ type: ErrorResponseDto, description: '' })
넹 추가했습니다아

2023-04-16 01:55 UTC, Kimhan-nah commented on backend/src/auth/auth.controller.ts
> +  ): Promise<NicknameSuccessResponseDto> {
ㅎㅎ.. 잊고 있었네용..ㅎㅎ 감삼다~~

2023-04-16 01:56 UTC, Kimhan-nah commented on backend/src/auth/auth.service.ts
> +    if (await this.authRepository.findOneBy({ id: authId })) {
넵넵..! 맞아요... 수정하겠습니다!

2023-04-16 01:58 UTC, Kimhan-nah commented on backend/src/common/constant.ts
> +export const DEFAULT_IMAGE = 'default image';
네에 확인했습니다아

2023-04-16 04:38 UTC, anso33 approved these changes
확인했습니다! 고생 많으셨어요!!!!

2023-04-16 04:49 UTC, jis-kim approved these changes
확인했습니다~! 수고하셨어요

2023-04-16 04:52 UTC, merged