✨ [Feature] update profile-image API
GhostPangPang/GhostPong pull request #77
Opened 2023-04-16 02:34 UTC by anso33

## Summary
유저의 프로필 이미지 변경하는 API 구현

## Describe your changes
- `user/image` api 구현
- repository의 find에 대해서 없는 데이터라는 에러를 처리할 때 개인적으로 return 값을 받아서 널 확인하는 방식을 좋아하는데요. 이렇게 되면 혹시나 find 실행시에 발생하는 다른 에러는 잡지 못할 수도 있나? 라는 생각이 드네요. 에러 처리에 대한 리뷰가 혹시 있으시면 가감없이 고고씽 해주십숑

- test-data.sql의 insert중 pk값에 대한 한나님의 조언을 받아 수정했습니다. 

## Issue number and link
close #71

2023-04-16 02:58 UTC, jis-kim requested changes
리뷰 확인해주세요!! 감사합니다 :)

2023-04-16 02:58 UTC, jis-kim commented on backend/src/user/user.service.ts
> +    if (!user) throw new NotFoundException('존재하지 않는 유저입니다. ');
이거 조건 `user === null` 로 바꿔주세요 (타입변환문제)

2023-04-16 02:58 UTC, jis-kim commented on backend/src/user/user.service.ts
> +      throw new ConflictException('이미지 업로드에 실패하였습니다.');
`ConflictException` 은 적절한 상태코드는 아닌 것 같습니다.. invalid 한 값은 앞에서 `validationPipe` 로 체크가 될 것 같고, DB 단에서 에러나는 부분밖에 없을 것 같아서 그냥 `try-catch` 문 없이 가도 좋을 것 같아요!

2023-04-16 02:58 UTC, jis-kim commented on backend/src/user/user.service.ts
>      const user = await this.userRepository.findOne({
이거 `findOneBy` 로 바꿔주세욥.!

2023-04-16 02:58 UTC, jis-kim commented on backend/src/user/user.controller.ts
> +  @ApiConflictResponse({ type: ErrorResponseDto, description: '이미지 처리 실패' })
밑의 throw 제거하시면 이 데코레이터도 제거해주세요!

2023-04-16 02:58 UTC, jis-kim commented on backend/src/user/user.controller.ts
> +  @ApiNotFoundResponse({ type: ErrorResponseDto, description: 'image value 잘못됨, 존재하지 않는 사용자' })
image value 잘못됐으면 400아닐까요..?! 파이프 단에서 걸러질 것 같습니다.

2023-04-16 03:02 UTC, anso33 commented on backend/src/user/user.service.ts
> +    if (!user) throw new NotFoundException('존재하지 않는 유저입니다. ');
화긴!

2023-04-16 03:03 UTC, anso33 commented on backend/src/user/user.service.ts
> +      throw new ConflictException('이미지 업로드에 실패하였습니다.');
화긴!

2023-04-16 03:16 UTC, anso33 commented on backend/src/user/user.service.ts
>      const user = await this.userRepository.findOne({
화긴!

2023-04-16 03:20 UTC, Kimhan-nah reviewed
확인 부탁드립니다아

2023-04-16 03:20 UTC, Kimhan-nah commented on database/test-data.sql
> +insert into USERS values(default, 'san', 42, 'asdfasdf');
users의 id는 auto increment가 아니라 auth id 사용하는 거라서 아마... default 안 될 거 같아요
여기는 임의의 값을 지정해야 될 거 같습니당

2023-04-16 03:20 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
전 그냥 `updateProfileImage` 함수에서 처리하는 게 더 괜찮다고 생각하는데 분리 시킨 이유가 있나용?

2023-04-16 03:34 UTC, anso33 commented on database/test-data.sql
> +insert into USERS values(default, 'san', 42, 'asdfasdf');
아 auth id 값을 넣어야할 것 같다는 말씀이시죠???

2023-04-16 03:36 UTC, anso33 commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
이거는 컨트롤러에서 호출하는 서비스 메서드를 db 접근하는 메서드로 바로 부르고 싶지 않아서 분리한건데 (그냥 개인 취향입니다ㅋㅋㅋ) 흠 뭐가 더 좋은지는 모르겠네여ㅠㅜ

2023-04-16 04:56 UTC, jis-kim approved these changes
확인했습니다~ 수고하셨습니다!

2023-04-16 04:56 UTC, jis-kim commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
전 개인적으로 `Update` 류 메소드는 id 로 하는 게 당연하다고 생각해서 (사실 달라지는 거 `Get` 밖에 없는듯..) ById 안붙일 것 같네요..ㅎㅎ tmi!! 메소드도 이정도는 분리 안할듯..

2023-04-16 05:03 UTC, anso33 commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ오바인가??ㅋㅋㅋㅋㅋ흠 모르겠어요!ㅋㅋㅋㅋㅋㅋㅋ

2023-04-16 05:11 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
저도 id로 하는게 당연하다고 생각해요 오히려 코드 보는데 좀더 헷갈리는 거 같아유 헤헷

2023-04-16 05:14 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
그리고 db  로직을 분리시키고 싶다면 findUserById는 updateProfileImage에 있어야 되는 거 아니에요??
분리가 어디까지 분리시켜야 되는 건지 헷갈리는군용..

2023-04-16 05:15 UTC, anso33 commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
아 메서드에서 name에서 ById 를 빼자고요?? 아니면 분리시키지 말고 메서드를 통합시키자는 의미일까유????

2023-04-16 05:18 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
통합시키는 걸 얘기한 거예용 아직까지 분리시키는 기준이 명확하지가 않은 거 같아서 더 헷갈리는 거 같아요 
분리할 때 방금 말씀드렸던 `findUserById`도 `updateProfileImage`, `updateProfileImageById`중에 어디 있어야 되는 건지 잘 모르겠어용

2023-04-16 05:19 UTC, Kimhan-nah commented on database/test-data.sql
> +insert into USERS values(default, 'san', 42, 'asdfasdf');
네네 맞아용 ~

2023-04-16 05:19 UTC, anso33 commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
음 근데 저는 repository.메서드() 이런식의 로직이 들어간 메서드를 분리 할때는 명확하게 설명이 들어가면 좋을 것 같아서 요런 로직만 들어가는 메서드로 나눌거면 By뭐뭐 로 하는지까지 적어주는게 낫다고 생각하는디 어떠세유?

만약에 두 함수를 그냥 뭉치자는 의미였다면은 By빼고 통합하겠읍니당

2023-04-16 05:21 UTC, anso33 commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
> 

아 이거는 데이터 update하기 전에 이 id가  존재하는 유저인지 확인해주기 위해서 필요해서 들어가 있웁니다! 제가 description에 적는 걸 깜박했네염ㅠㅜ

2023-04-16 05:25 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +  async updateProfileImageById(myId: number, imageUrl: string): Promise<void> {
repository의 delete, find처럼 By가 의미있는 경우에 사용하자는 거죠?? 저같은 경우는 insert에서 딱히 By가 필요없는데
현재 `createUSer`이라는 method가 있고 그걸 분리시키면 함수명이 동일해져서..어떻게 통일시켜야 할까욤..?

2023-04-16 06:03 UTC, Kimhan-nah approved these changes
service에서 repository 분리는 각자 취향대로...ㅎㅎ ㅋㅋㅋㅋ 대신 각자 취향의 기준이 명확해야 됩니다!!

2023-04-16 07:47 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +    const user = await this.userRepository.findOneBy({
여기서 그냥 userId가 존재하는지 `checkExistUser`로 확인하면 안 되나여??

2023-04-17 02:39 UTC, jis-kim approved these changes
수정사항 반영 확인했습니다. 수고하셨습니다!

2023-04-17 02:50 UTC, merged