:sparkles: [Feature] block-user API
GhostPangPang/GhostPong pull request #93
Opened 2023-04-18 07:47 UTC by anso33

## Summary
유저를 차단하는 API 구현

## Describe your changes
두 api에 대한 로직이 매우 흡사하여 한번에 pr 합니다.
 
- `blocked/{user_id}` 구현
- userService에 구현한 findExistUser를 가져다 썼습니다. 그런데 nickname으로 찾아올때도 같은 일을 하는 함수가 필요해서 By를 붙여 구분하였습니다. 
- `blocked?nickname=""` 구현

- 이름이 좀 긴데 줄이기엔 애매해서 그냥 놔두었습니다.

## Issue number and link
- close #78 
- close #79

2023-04-18 09:43 UTC, Kimhan-nah reviewed
내가 이미 상대로부터 차단되어 있을 때 차단 시도하는 경우 어떻게 되나용??

2023-04-18 09:43 UTC, Kimhan-nah commented on backend/src/blocked/blocked.controller.ts
> +  @ApiParam({ name: 'userId', description: '차단할 사람 아이디' })
Post는 기본 status code가 201이라서 `  @HttpCode(HttpStatus.OK)`로 200 바꿔줘야 됩니당!

2023-04-18 09:43 UTC, Kimhan-nah commented on backend/src/blocked/blocked.service.ts
> +  async checkExistBlockedUser(userId: number, blockedUserId: number): Promise<void> {
내가 상대로부터 차단되어 있는 상태는 저희 따로 처리 안해도 됐나요??

2023-04-18 09:43 UTC, Kimhan-nah commented on backend/src/blocked/blocked.controller.ts
> +  @ApiParam({ name: 'userId', description: '차단할 사람 아이디' })
앗 바꼈군요 ㅎ 확인했습니다

2023-04-18 09:45 UTC, anso33 commented on backend/src/blocked/blocked.controller.ts
> +  @ApiParam({ name: 'userId', description: '차단할 사람 아이디' })
앞!! 벌써 확인 중이셨다닠ㅋㅋㅋㅋ 방금 아차 해서 바꿨습니당ㅋㅋㅋ 화긴!

2023-04-18 09:49 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +  async checkExistBlockedUser(userId: number, blockedUserId: number): Promise<void> {
오... 근데 저장되는 db가 userId와 blockedUserId 로 되어있기도 하고 
차단할 때 상대가 날 차단했는지에 대한 정보가 관련없어보여서 
내가 차단했던 목록에 대해서만 확인하면 될 것 같아요!

2023-04-18 09:49 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +    await this.checkExistBlockedUser(myId, userId);
오 감사합니당!! 추가할게요!

2023-04-18 11:53 UTC, Kimhan-nah reviewed
수정 사항이 발견되었어욤...ㅎㅎ

2023-04-18 11:53 UTC, Kimhan-nah commented on backend/src/blocked/blocked.service.ts
> +    }
방금 발견했는데 `userId` 유효 검사 해야될 거 같네요..ㅠ..ㅠ

2023-04-18 11:53 UTC, Kimhan-nah commented on backend/src/blocked/blocked.service.ts
> +    if (friendship !== null) {
조건문 없이 그냥 return friendship해도 null이면 null 리턴하는데 이건 @jis-kim 이 나중에 리팩토링할 때 수정하는 걸로 해도 좋아요 ㅎㅎ

2023-04-18 12:12 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +    }
이거 blockUser 부르기 전에 유효성 검사 하고 있읍니당

2023-04-18 12:13 UTC, anso33 commented on backend/src/blocked/blocked.service.ts
> +    if (friendship !== null) {
아 그러네요ㅋㅋㅋ 고쳐놓겠습니답

2023-04-18 12:29 UTC, jis-kim requested changes
수고하셨습니다!! 코멘트 한 부분 확인해주시고 `private` 으로 지정할 수 있는 메소드는 변경해주시면 좋을 것 같아요!!

2023-04-18 12:29 UTC, jis-kim commented on backend/src/blocked/blocked.controller.ts
> +  @ApiNotFoundResponse({ type: ErrorResponseDto, description: '유저 없음' })
뷰에서 날 가능성이 적은 에러라서 생략해도 될 것 같습니다!

2023-04-18 12:29 UTC, jis-kim commented on backend/src/blocked/blocked.controller.ts
> +    description: '이미 차단함 유저, 스스로를 차단할 수 없음',
스스로를 차단하는 경우도 뷰에서 날 가능성이 적은 경우라 생략해도 될 듯 합니다!

2023-04-18 12:29 UTC, jis-kim commented on backend/src/user/user.service.ts
> +      nickname: userNickname,
개인취향이긴 한데 위에 parameter 를 `nickname` 으로 하면 여기 `nickname: userNickname` 이 아니라 그냥 `nickname` 으로도 가능합니다.ㅎㅎ 
```ts
async findExistUserByNickname(nickname: string): Promise<User> {
  const user = await this.userRepository.findOneBy({
    nickname
  });
  ...
 }
```

2023-04-18 12:37 UTC, anso33 commented on backend/src/blocked/blocked.controller.ts
> +  @ApiNotFoundResponse({ type: ErrorResponseDto, description: '유저 없음' })
url로 넣으면 발생할 수 도 있는 에러라고 생각해서 넣었습니다!
그런데 url로도 못넣는다고 하더라도 에러 처리를 생략하면 뭐가 좋은가요? 디비에 접근할 일을 줄여서 좋은건가요?
이런면이 아니라면 에러처리를 줄일 필요가 뭔지 잘 모르겠어염!!!!

2023-04-18 12:38 UTC, jis-kim commented on backend/src/blocked/blocked.controller.ts
> +  @ApiNotFoundResponse({ type: ErrorResponseDto, description: '유저 없음' })
아 에러처리를 생략하는 것이 아니고 데코레이터만 제거해주시면 됩니다. 쏘리쏘리!!! 데코레이터를 뷰에서만 보이는 걸로 제한하려는 이유는 코드가 너무 더러워지기 때문입니다.. 이거 완전 데코레이터 코딩...

2023-04-18 12:39 UTC, anso33 commented on backend/src/blocked/blocked.controller.ts
> +  @ApiNotFoundResponse({ type: ErrorResponseDto, description: '유저 없음' })
아하 !!! 인정이염 인정인정인정인정인정인정인정인정인정인정인정인정인정인정인정!!
좋아요 좋아 앞으로도 반영합니다.

2023-04-18 13:30 UTC, jis-kim approved these changes
너무 깔끔해요 굿!!^__^ 수고하셨어요!!

2023-04-19 01:54 UTC, Kimhan-nah approved these changes
확인완료욤~

2023-04-19 01:54 UTC, Kimhan-nah commented on backend/src/blocked/blocked.service.ts
> +    const friendship = await this.checkIsFriend(myId, userId);
@jis-kim 님이 오늘 친구 삭제 API 개발하시면서 delete 로직 구현해주시면 아마 이거 다 필요없고 그냥 delete 함수 호출하면 될 거 같아용 거기서 어차피 친구 관계 맞는지도 확인하면 될듯??

2023-04-19 02:04 UTC, merged

2023-04-19 02:10 UTC, jis-kim commented on backend/src/blocked/blocked.service.ts
> +    const friendship = await this.checkIsFriend(myId, userId);
태스크가 늘었군용?호호
- #82