:sparkles: [Feature] change-nickname API
GhostPangPang/GhostPong pull request #95
Opened 2023-04-18 09:19 UTC by anso33

## Summary
닉네임 바꾸는 API 구현

## Describe your changes
- auth에 있던 user 로직 userService로 옮겼습니다. 
  userRepository를 사용하는 로직만 나눠서 옮겼습니다. 어렵네요.

- `user/nickname` 구현
- dto 내용이 같은데 일단 response, request 나눴습니다. 합쳐야 한다는 의견이 있으신 분은 의견 남겨주세염!
- dto 정규표현식이용해서 닉네임에 한글, 영어. 숫자만 가능하도록 했습니다. 다만 "ㅏ" 같은 한글은 입력 오류로 처리됩니다.  
- 에러날 부분을 중복된 닉네임밖에 찾지 못했는데 제가 놓친 것이 있다면 알려주세요!

## Issue number and link
- close #94

2023-04-18 09:58 UTC, Kimhan-nah commented on backend/src/auth/auth.service.ts
> -    await this.checkAlreadyExist(authId);
이건 사라지면 안 될 거 같아용..!

2023-04-18 10:12 UTC, anso33 commented on backend/src/auth/auth.service.ts
> -    await this.checkAlreadyExist(authId);
아 이거 userAlreadyExtist가  userRepository 쓰길래 userService.createUser안에 넣어서 userService로 뺐습니당 살아있아요!!

2023-04-18 11:24 UTC, Kimhan-nah reviewed
확인 부탁드립니다아

2023-04-18 11:24 UTC, Kimhan-nah commented on backend/src/user/user.controller.ts
>  }
닉네임 초기 설정이 추가가 안 된 것 같아용 (service의 `createUser` 함수가 사용되지 않았어요)
POST 로 endpoint는 `/user` 입니다!
Notion API 설계에 수정해뒀으니 참고하시면 될 거 같아요

2023-04-18 11:24 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +  async checkAlreadyExist(authId: number): Promise<void> {
이런 함수들이 외부에서 사용할 일이 없다면 `private`로 해도 좋을 것 같아요! 아마 이전에 저는 `private`로 했었는데 지금은 어떻게 될 지 잘 모르겠습니다 ㅎ.ㅎ

2023-04-18 11:26 UTC, Kimhan-nah commented on backend/src/auth/auth.service.ts
> -    await this.checkAlreadyExist(authId);
아아 확인했습니다!

2023-04-18 11:28 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +  async checkAlreadyExist(authId: number): Promise<void> {
아 이건 외부에서 사용되고 있군요! 다른 함수들 확인부탁드립니다~~

2023-04-18 11:34 UTC, anso33 commented on backend/src/user/dto/update-nickname-request.dto.ts
> +  @Matches(RegExp('^[가-힣a-zA-Z0-9]*$'))
닉네임 숫자, 영어, 한글만 들어오게 확인해주는 validation입니다!
description에 적어두었숩니당~

2023-04-18 11:34 UTC, Kimhan-nah commented on backend/src/auth/auth.service.ts
> -    await this.checkAlreadyExist(authId);
아 근데 domain이 `auth` 에서 `user`로 바껴서 auth controller에 있는 것들도 `user` controller에 옮겨야 될 거 같아요!

2023-04-18 11:35 UTC, Kimhan-nah commented on backend/src/auth/auth.service.ts
> -    await this.checkAlreadyExist(authId);
`auth.controller` 파일 가보시면 제가 TODO 주석 달아둔거 있을 거예요

2023-04-18 11:40 UTC, Kimhan-nah commented on backend/src/user/user.service.ts
> +    });
제가 createUser에서 생성만 해주고 `auth` table의 `status` column에 `UNREGISTER`을 `REGISTER`로 update 시키는 걸 깜빡 했습니다..ㅎㅎ 추가 부탁드립니다아~~

2023-04-18 11:54 UTC, anso33 commented on backend/src/auth/auth.service.ts
> -    await this.checkAlreadyExist(authId);
확인했습니다!

2023-04-18 11:58 UTC, anso33 commented on backend/src/user/user.service.ts
> +  async checkAlreadyExist(authId: number): Promise<void> {
엄 다른 애들은 다른데서도 써서 일단 이것만 바꿨습니다. 나중에 구현할 때 참고하면서 할게염!

2023-04-18 11:58 UTC, anso33 commented on backend/src/user/user.service.ts
> +    });
확인했습니다ㅏ

2023-04-18 13:20 UTC, jis-kim requested changes
Auth 랑 많이 엮여있어서 복잡했을 것 같네요 수고하셨어요!! 네이밍만 확인 부탁드립니다. 그리고 전 dto 나누는 쪽 괜찮다고 생각합니다... 나중에 프론트와 공용으로 사용하기 위해 `types` 를 새로 만들어서 뺄 건데 거기서 추상화하고 여기서 이름이랑 validator 적용 여부만 다르게 해서 `implements` 받으면 될 것 같아요!

2023-04-18 13:20 UTC, jis-kim commented on backend/src/auth/auth.service.ts
>      if ((await this.authRepository.findOneBy({ id: authId })) === null) {
여기서 unregister 상태인지도 체크해야 할 것 같습니다!

2023-04-18 13:20 UTC, jis-kim commented on backend/src/user/user.service.ts
> +    await this.checkAlreadyExist(authId);
뭐가 alreadyExist 인지 정보가 있었으면 좋겠습니다... `checkAlreadyExistUser` 제안드려요!

2023-04-18 13:20 UTC, jis-kim commented on backend/src/user/user.service.ts
> +    await this.authService.checkAuthId(authId);
이것은 auth id 를..? auth id 로 체크한다는 걸까요? `checkAuthId`는 `authId` 로 `Auth` 가 있는지 체크하는 것 같고 `checkAlreadyExist` 는 `authId` 로 `User` 가 있는 지 체크하는 함수 같은데 이름만 보면 뭐가뭔지 구분이 잘 안갑니다.. 🥲 전자는 `Auth` 가, 후자는 `User` 가 이름에 들어가면 더욱 좋겠습니다!

2023-04-18 13:30 UTC, anso33 commented on backend/src/auth/auth.service.ts
>      if ((await this.authRepository.findOneBy({ id: authId })) === null) {
이거 auth_id 있는데 UNREGISTERD 여야 하는거죠? @Kimhan-nah 
status는 왜 체크해야 하죠?!?!?

2023-04-18 13:34 UTC, anso33 commented on backend/src/auth/auth.service.ts
>      if ((await this.authRepository.findOneBy({ id: authId })) === null) {
아 id가 있는데 status가 레지스터 상태이면 에러 처리해야겠죠? 지수님이 말씀하신건 요부분인가요?

2023-04-18 13:34 UTC, jis-kim commented on backend/src/auth/auth.service.ts
>      if ((await this.authRepository.findOneBy({ id: authId })) === null) {
그럴 가능성은 매우 적겠지만 REGISTERED 인 사람이 uri 를 알아내서 요청을 보낼 수 있지 않을까요? 막아줘야 한다고 생각합니다

2023-04-19 02:00 UTC, jis-kim requested changes
리뷰 확인 부탁드립니다!

2023-04-19 02:00 UTC, jis-kim commented on backend/src/auth/auth.service.ts
> +    if ((await this.authRepository.findOneBy({ id: authId, status: AuthStatus.REGISTERD })) !== null) {
이 부분 한 번의 메소드 콜으로 처리가능할 것 같아요! 앞에서 `findOneBy({id: authId});` 한 값을 저장했다가 
1. `null` 이면 `NotFoundException`
2. `status` 가 `AuthStatus.REGISTERED` 이면 `ConflictException` 

으로 처리하는 방법 제안 드립니다.

2023-04-19 02:00 UTC, jis-kim commented on backend/src/user/user.service.ts
> +    await this.authService.changeAuthStatus(authId);
여기 Transaction 처리가 필요할 것 같아요! user 만 insert 되고 `changeAuthStatus` 가 터지면 `authId` 로 만들어진 유저만 있고 정작 `auth` 는 `UNREGISTERED` 상태가 되는 불상사가 일어날 것 같습니다....
[nest transaction 문서](https://docs.nestjs.com/techniques/database#typeorm-transactions) , [typeorm transaction 문서](https://typeorm.io/transactions#creating-and-using-transactions)

2023-04-19 02:00 UTC, jis-kim commented on backend/src/user/user.service.ts
> +    await this.authService.changeAuthStatus(authId);
FIX 표시만 하고 일단 다음작업 진행합시다!

2023-04-19 02:02 UTC, Kimhan-nah approved these changes
굳굳~~~ 하고 approve했는데 reject 되었군...ㅎㅋㅋㅋㅋ 홧팅 ..~~~

2023-04-19 02:05 UTC, Kimhan-nah commented on backend/src/auth/auth.service.ts
> +    if ((await this.authRepository.findOneBy({ id: authId, status: AuthStatus.REGISTERD })) !== null) {
이건 제가 했던 부분일텐데..ㅋㅋㅋㅋㅋㅋㅋㅋ

2023-04-19 02:06 UTC, Kimhan-nah commented on backend/src/auth/auth.service.ts
> +    if ((await this.authRepository.findOneBy({ id: authId, status: AuthStatus.REGISTERD })) !== null) {
가 아니군? 추가된 것이군?

2023-04-19 02:06 UTC, Kimhan-nah commented on backend/src/auth/auth.service.ts
> +    if ((await this.authRepository.findOneBy({ id: authId, status: AuthStatus.REGISTERD })) !== null) {
그치만 나의 task 였던 것...ㅎ... 소현쨩 미얀 >< 💖

2023-04-19 04:40 UTC, anso33 commented on backend/src/user/user.service.ts
> +    await this.authService.changeAuthStatus(authId);
이것은 다음 pr 때 반영해서 수정하도록 하겠습니다! 감사합니당

2023-04-20 07:45 UTC, jis-kim approved these changes
수고하셨어요!!><

2023-04-20 07:45 UTC, jis-kim commented on backend/src/user/user.module.ts
> +  providers: [UserService, AuthService],
이거 `AuthModule` 에서 `AuthService` 를 export 하고 `AuthModule` 을 `import` 하는 방식으로 통일할까요?

2023-04-20 08:09 UTC, anso33 commented on backend/src/user/user.module.ts
> +  providers: [UserService, AuthService],
옙 다음 pr에 반영하겠읍니다.!!

2023-04-20 08:13 UTC, merged